spring.application.name=ai
spring.ai.google.genai.api-key=${API_KEY}
spring.ai.google.genai.embedding.api-key=${API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768

#Database && JPA
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## Reduce maximum pool size to 2
spring.datasource.hikari.maximum-pool-size=2

# Keep only 1 connection alive when idle
spring.datasource.hikari.minimum-idle=1

# How long to wait for a connection before failing (15 seconds)
spring.datasource.hikari.connection-timeout=15000

# Prevent old connections from sitting open indefinitely
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#PGVector
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

jwt.secret=${SECRET_KEY}
logging.level.root=DEBUG

server.port=8081
spring.devtools.livereload.port=35729

